"""prompts_user_prompt_template_nullable

Revision ID: c8f68add86f4
Revises: 004
Create Date: 2026-06-26 02:02:07.896576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f68add86f4'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'user_prompt_template',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'user_prompt_template',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
