import re
from pathlib import Path

from generators.services.base import BaseGenerator


def _base_requirements(svc) -> list[str]:
    deps = [
        "structlog>=24.0.0",
        "python-dateutil>=2.8.2",
        "pydantic>=2.0.0",
        "pydantic-settings>=2.0.0",
    ]
    if svc.grpc.enabled or svc.grpc_client.enabled:
        deps += [
            "grpcio>=1.60.0",
            "grpcio-tools>=1.60.0",
            "grpcio-reflection>=1.60.0",
            "protobuf>=4.25.0",
            "mypy-protobuf>=3.5.0",
        ]

    if svc.postgres.enabled:
        deps += [
            "sqlalchemy[asyncio]>=2.0",
            "asyncpg>=0.29.0",
            "alembic>=1.13.0",
        ]
    if svc.minio.enabled:
        deps.append("minio>=7.2.0")

    if svc.vault.enabled:
        deps.append("hvac>=2.0.0")

    if svc.kafka_producer.enabled or svc.kafka_consumer.enabled:
        deps.append("aiokafka>=0.10.0")

    if svc.observability.enabled:
        deps += [
            "opentelemetry-sdk>=1.22.0",
            "opentelemetry-api>=1.22.0",
            "opentelemetry-exporter-otlp-proto-grpc>=1.22.0",
            "opentelemetry-instrumentation-grpc>=0.43b0",
        ]

    if svc.scheduler.enabled:
        deps.append("croniter>=2.0.0")

    return deps


def _dedup_and_sort(deps: list[str]) -> list[str]:
    seen: dict[str, str] = {}

    for d in deps:
        name = re.split(r"[<>=!~]", d)[0].strip()

        if name not in seen:
            seen[name] = d

    return sorted(seen.values(), key=lambda d: re.split(r"[<>=!~]", d)[0].strip())


def _load_user_requirements(path: Path) -> list[str]:
    if not path.exists():
        return []

    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()

        if stripped and not stripped.startswith("#"):
            lines.append(stripped)

    return lines


class RequirementsGenerator(BaseGenerator):
    def generate(self) -> None:
        base = _base_requirements(self.svc)

        user_req_path = self.output.parent / "requirements.txt"
        if not user_req_path.exists():
            user_req_path.write_text("# User dependencies — add your packages here\n", encoding="utf-8")
            self.files_written += 1

        user = _load_user_requirements(user_req_path)
        merged = _dedup_and_sort(base + user)

        lines = [
            "# ---------------------------------------------------------------------------",
            "# Auto-generated by codegen — do not edit manually.",
            "# To regenerate: codegen generate",
            "# ---------------------------------------------------------------------------",
            "",
        ]
        if user:
            lines.append(f"-r ../requirements.txt")
            lines.append("")

        lines += merged

        content = "\n".join(lines)
        content += "\n"

        self.write("requirements.txt", content)
